name: Notarize Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  notarize:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter build windows --release
      - name: Notarize with SignPath
        uses: SignPath/Submit-Signing-Request@v1
        with:
          project-slug: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
          access-token: ${{ secrets.SIGNPATH_ACCESS_TOKEN }}
          artifact-path: build/windows/runner/Release/**/*.exe
          signing-policy-slug: ${{ secrets.SIGNPATH_SIGNING_POLICY_SLUG }}
