name: Code Quality

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n
      - run: dart format --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
      - name: Run Dart Code Metrics
        run: |
          dart pub global activate dart_code_metrics
          dart pub global run dart_code_metrics:metrics analyze lib
