name: Release

on:
  push:
    workflow_run:
      workflows:
        - "Build"
      types: [completed]
    if: ${{ github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v') }}

jobs:
  release:
    name: Create Release
    needs: [build-android, build-ios, build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/android-apk/app-release.apk
            artifacts/ios-app/Runner.app
            artifacts/macos-app/VPNclient.app
            artifacts/windows-app/VPNclient.exe
            artifacts/linux-app/bundle/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
